TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install databases, templates & substitutions like this
DB += hallc.db
DB += simulate.db
DB += run_settings.db
DB += daq_run.db
DB += circle.db
DB += dbExample1.db
DB += dbExample2.db
DB += test1Version.db
DB += dbSubExample.db
DB += user.substitutions

# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD EXTRA GNUMAKE RULES BELOW HERE

